groups:
  - name: container_alerts
    rules:
      - alert: ServiceDown
        expr: up == 0
        for: 15s
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is DOWN"

      - alert: ApplicationErrorsDetected
        expr: sum(rate(app_http_errors_total[1m])) > 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Application HTTP errors are being returned"
