groups:
  - name: container_alerts
    rules:
      - alert: ServiceDown
        expr: up == 0
        for: 15s
        labels:
          severity: critical
        annotations:
          summary: "Service {{ $labels.job }} is DOWN"